tinkoff-parameters:
  AccountId: 
  APIToken: 
  EndPoint: invest-public-api.tinkoff.ru:443
  AppName: invest-api-go-sdk
  DisableResourceExhaustedRetry: false
  DisableAllRetry: true
  MaxRetries: 3
candle-duration-ns: 60000000000
candle-scrapper-mode: false
tg-token: 
chat-id: 
admin-id:
redis-log:
  address: localhost:6379
  password: mypass
  db: 4
redis-change:
  address: localhost:6379
  password: mypass
  db: 5
